### PR TITLE
Improvements in the README for clearer installation

### PR DESCRIPTION
**Pull request by DougBeney**
Thanks for creating this project! Just thought I'd share my idea of how to make installation clearer and easier for the user. I also made the installation instructions closer to the top of the README file so the user doesn't have to scroll as much. Cheers!

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Thank you @DougBeney have you not tried VERSION_2 yet? Current version covers 5641 referrers and 504 bots.

**Comment by DougBeney** [comment]
Thanks for accepting! I actually haven't yet. I'll look into it. :)

**Comment by DougBeney** [comment]
Why hasn't version 2 replaced version 1 yet?

**Comment by mitchellkrogza** [comment]
@mariusv been very quiet for months, hope he is okay. I don't want to just
hijack the repo so initially when he gave me contributor access I said I
would make it a separate version.

**Comment by DougBeney** [comment]
Ah, ok.

**Pull request merged**
