### PR TITLE
18 more bad referrers

### PR DESCRIPTION
**Pull request by elaur**
love-baby.cz
produkto.net
kadashihotel.com
foto-sisek.porngalleries.top
xaijo.com
yur-p.ru
prlog.ru
kashubadesign.ru
slim.sellany.ru
xdoza.com
mcar.in.ua
greendream.com.ua
intimshop-fantasy.ru
battlecarnival.su
expertblog.info
fable.in.ua
iptool.xyz
toys.erolove.in

### CODE REVIEW

**Comment by mitchellkrogza** [comment]
Merged in https://github.com/mariusv/nginx-badbot-blocker/pull/80 Thanks for contributing

**Comment by mitchellkrogza** [comment]
Funny thing .... 15 of those were already in my lists this morning from my logs. Seems when they hit your sites they hit mine too. Keep them coming 👍

**Comment by elaur** [comment]
Uh 😟  this is my list from the last week. Comming back next week with more.

**Comment by mitchellkrogza** [comment]
Many of those too from over a week ago, I've been falling behind with reading my email logs as my Dad has been very ill for the past 3 months. Not in a good state. Thankfully these projects keep my mind off things, spending hours at the PC keeping my mind off family troubles.

**Comment by mitchellkrogza** [comment]
I've duplicated the bad referers list into a seperate project https://github.com/mitchellkrogza/Badd-Boyz-Hosts and now also merged into https://github.com/StevenBlack/hosts

**Pull request closed without merging**
